<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default scoreboard</name>
  <uuid>140c3d24-0b69-4b29-8942-41edaba0465b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'ML model invocation' is in error
then
set decision to a new Scoreboard where
	the Confidence is 0,
	High risk is true,
	the Segment is "Unknown" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
