<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>machineLearningScoreboard</name>
  <uuid>07a4cc5f-c58d-49c1-861e-c2856396d232</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to predict( 'Input mapping' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
